minor fixes

diff --git a/CPP09/ex02/Makefile b/CPP09/ex02/Makefile
--- a/CPP09/ex02/Makefile
+++ b/CPP09/ex02/Makefile
@@ -18,6 +18,7 @@ OBJ_DIR		:=	obj
 OBJS		:=	$(SRCS:$(SRC_DIR)/%.cpp=$(OBJ_DIR)/%.o)
 
 TMP_DIR		:=	tmp
+TMP_FILES	:=	# If files are created outside of TMP_DIR folder
 
 REMOVE		:=	rm -rf
 OS			:=	$(shell uname)
@@ -37,7 +38,7 @@ endif
 
 # **************************************************************************** #
 
-all: $(NAME)
+all: $(NAME) ## Compile the Project and create the executable
 
 $(NAME): $(OBJS) $(INCS) $(TPP_FILES)
 	@echo "[$(BOLD)$(PURPLE)$(NAME)$(RESET)]\\t$(GREEN)ready$(RESET)"
@@ -51,7 +52,7 @@ $(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp $(INCS) $(TPP_FILES) | $(OBJ_DIR)
 $(OBJ_DIR):
 	@mkdir -p $(OBJ_DIR)
 
-clean:
+clean: ## Remove folder containing object files
 	@if [ -n "$(wildcard $(OBJ_DIR))" ]; then \
 		$(REMOVE) $(OBJ_DIR); \
 		echo "[$(BOLD)$(PURPLE)$(NAME)$(RESET)] \
@@ -61,7 +62,7 @@ clean:
 		$(YELLOW)No object files to remove$(RESET)"; \
 	fi
 
-fclean: clean
+fclean: clean ## 'clean' + Remove executable
 	@if [ -n "$(wildcard $(NAME))" ]; then \
 		$(REMOVE) $(NAME); \
 		echo "[$(BOLD)$(PURPLE)$(NAME)$(RESET)] \
@@ -71,15 +72,89 @@ fclean: clean
 		$(YELLOW)No executable to remove$(RESET)"; \
 	fi
 
-re: fclean all
+re: fclean all ## 'fclean' + 'all' (Recompile the project)
 
 .PHONY: all clean fclean re
+# **************************************************************************** #
+# ---------------------------------- UTILS ----------------------------------- #
+# **************************************************************************** #
+.DEFAULT_GOAL	:= all
+
+.DEFAULT: ## Handle invalid targets
+	$(info make: *** No rule to make target '$(MAKECMDGOALS)'.  Stop.)
+	@$(MAKE) help $(NPD)
+
+help: ## Display available targets
+	@echo "\nAvailable targets:"
+	@awk 'BEGIN {FS = ":.*##";} \
+		/^[a-zA-Z_0-9-]+:.*?##/ { \
+			printf "  $(CYAN)%-15s$(RESET) %s\n", $$1, $$2 \
+		} \
+		/^##@/ { \
+			printf "\n$(BOLD)%s$(RESET)\n", substr($$0, 5) \
+		}' $(MAKEFILE_LIST)
+
+GENERATED_SEQUENCE	:= $(TMP_DIR)/generated_sequence.txt
+SEQUENCE_HYPERLINK	:= \033]8;;file://$(GENERATED_SEQUENCE)\a$(GENERATED_SEQUENCE)\033]8;;\a
+
+rand: all | $(TMP_DIR)
+	@read -p "How many values should we generate for $(NAME)? " NUM_VALUES; \
+	if [ -z "$$NUM_VALUES" ]; then \
+		echo "No value entered. Running $(NAME) without arguments."; \
+		./$(NAME); \
+	elif [ $$NUM_VALUES -gt 0 ]; then \
+		if [ "$(shell uname)" = "Linux" ]; then \
+			RAND_SEQUENCE=$$(shuf -i 1-$$NUM_VALUES -n $$NUM_VALUES | tr '\n' ' '); \
+		else \
+			RAND_SEQUENCE=$$(awk -v n=$$NUM_VALUES 'BEGIN{srand(); max=2*n; \
+				for(i=0; i<n; i++) { \
+					do { \
+						r=int(rand()*max); \
+					} while(r in seen || r < 0); \
+					seen[r]=1; \
+					printf r" "; \
+				} \
+			}'); \
+		fi; \
+		printf "$(UP)$(ERASE_LINE)"; \
+		if [ $$NUM_VALUES -gt 40 ]; then \
+			echo $$RAND_SEQUENCE > $(GENERATED_SEQUENCE); \
+			echo "Generated input sequence written in $(BLUE)$(SEQUENCE_HYPERLINK)$(RESET)\n"; \
+		fi; \
+		./$(NAME) $$RAND_SEQUENCE; \
+	else \
+		echo "Error: Invalid number of values, must be greater than 0."; \
+		exit 1; \
+	fi
+
+# RAND_SEQUENCE=$$(awk -v n=$$NUM_VALUES 'BEGIN{srand(); for(i=1; i<=n; i++) a[i]=i; for(i=n; i>0; i--){j=int(rand()*i)+1; printf a[j]" "; a[j]=a[i]}}'); # <- N shuffled numbers from 1 to N
+# RAND_SEQUENCE=$$(awk -v n=$$NUM_VALUES 'BEGIN{srand(); max=2*n; for(i=0; i<n; i++){do{r=int(rand()*max)} while(r in seen || r < 0); seen[r]=1; printf r" "}}'); <- N shuffled numbers from 0 to N*2 ?
+
+run: rand ## Compile and run the executable with randomized sequence argument
+
+debug: C_FLAGS += -DDEBUG=true
+debug: re ## 're' + Set 'DEBUG' macro to 'true' to print more info in executable
+
+$(TMP_DIR):
+	@mkdir -p $(TMP_DIR)
+
+ffclean: fclean ## 'fclean' + Remove temporary files and folders
+	@if [ -n "$(wildcard $(TMP_DIR))" ]; then \
+		$(REMOVE) $(TMP_DIR); \
+		echo "[$(BOLD)$(PURPLE)$(NAME)$(RESET)] \
+		$(GREEN)Temporary files removed$(RESET)"; \
+	else \
+		echo "[$(BOLD)$(PURPLE)$(NAME)$(RESET)] \
+		$(YELLOW)No temporary files to remove$(RESET)"; \
+	fi
+
+.PHONY: help rand run debug ffclean
 # **************************************************************************** #
 # ---------------------------------- PDF ------------------------------------- #
 # **************************************************************************** #
 GIT_URL		:= https://github.com/SaydRomey/42_ressources
 
-pdf:
+pdf: ## Obtain the PDF instructions for this project and open it
 	@echo "Obtaining pdf..."
 	@$(MAKE) get_pdf MODULE=cpp09 $(NPD)
 
@@ -96,11 +171,11 @@ get_pdf: | $(TMP_DIR)
 CPP_REF_URL		:=	https://cplusplus.com/reference/
 CPP_TUTO_URL	:=	https://cplusplus.com/doc/oldtutorial/
 
-ref:
+ref: ## Open documentation (https://cplusplus.com/reference/)
 	@echo "Opening cplusplus reference's url..."
 	@$(OPEN) $(CPP_REF_URL);
 
-tuto:
+tuto: ## Open tutorial (https://cplusplus.com/doc/oldtutorial/)
 	@echo "Opening cplusplus oldtutorial's url..."
 	@$(OPEN) $(CPP_TUTO_URL);
 
@@ -110,70 +185,19 @@ tuto:
 # **************************************************************************** #
 REPO_LINK	:= https://github.com/SaydRomey/CPP
 
-repo:
+repo: ## Open author's CPP repo on github
 	@echo "Opening $(AUTHOR)'s github repo..."
 	@$(OPEN) $(REPO_LINK);
 
-.PHONY: repo
-# **************************************************************************** #
-# ---------------------------------- UTILS ----------------------------------- #
-# **************************************************************************** #
-GENERATED_SEQUENCE	:= $(TMP_DIR)/generated_sequence.txt
+gitignore: ## Create the .gitignore file with multi-line variable in 'TEMPLATES' section
+	@echo "Creating gitignore file..."
+	@echo "$$GITIGNORE_CONTENT" > .gitignore
 
-SEQUENCE_HYPERLINK	:= \033]8;;file://$(GENERATED_SEQUENCE)\a$(GENERATED_SEQUENCE)\033]8;;\a
-
-
-rand: all | $(TMP_DIR)
-	@read -p "How many values should we generate for $(NAME)? " NUM_VALUES; \
-	if [ -z "$$NUM_VALUES" ]; then \
-		echo "No value entered. Running $(NAME) without arguments."; \
-		./$(NAME); \
-	elif [ $$NUM_VALUES -gt 0 ]; then \
-		if [ "$(shell uname)" = "Linux" ]; then \
-			RAND_SEQUENCE=$$(shuf -i 1-$$NUM_VALUES -n $$NUM_VALUES | tr '\n' ' '); \
-		else \
-			RAND_SEQUENCE=$$(jot -r $$NUM_VALUES 1 $$NUM_VALUES | tr '\n' ' '); \
-		fi; \
-	printf "$(UP)$(ERASE_LINE)"; \
-		if [ $$NUM_VALUES -gt 40 ]; then \
-			echo $$RAND_SEQUENCE > $(GENERATED_SEQUENCE); \
-			echo "Generated input sequence written in $(BLUE)$(SEQUENCE_HYPERLINK)$(RESET)\n"; \
-		fi; \
-		./$(NAME) $$RAND_SEQUENCE; \
-	else \
-		echo "Error: Invalid number of values, must be greater than 0."; \
-		exit 1; \
-	fi
-
-
-# ARG	:= 3 5 9 7 4
-
-# run: all
-# 	./$(NAME) $(ARG)
-
-run: rand
-
-debug: C_FLAGS += -DDEBUG=true
-debug: re
-
-$(TMP_DIR):
-	@mkdir -p $(TMP_DIR)
-
-ffclean: fclean
-	@if [ -n "$(wildcard $(TMP_DIR))" ]; then \
-		$(REMOVE) $(TMP_DIR); \
-		echo "[$(BOLD)$(PURPLE)$(NAME)$(RESET)] \
-		$(GREEN)Temporary files removed$(RESET)"; \
-	else \
-		echo "[$(BOLD)$(PURPLE)$(NAME)$(RESET)] \
-		$(YELLOW)No temporary files to remove$(RESET)"; \
-	fi
-
-.PHONY: rand run debug ffclean
+.PHONY: repo gitignore
 # **************************************************************************** #
 # --------------------------------- CLASS ------------------------------------ #
 # **************************************************************************** #
-class:
+class: ## Script to automate class creation
 	@echo "Enter the class name: "; \
 	read classname; \
 	classname_upper=`echo $$classname | tr a-z A-Z`; \
@@ -202,6 +226,41 @@ class:
 .PHONY: class
 # **************************************************************************** #
 # ------------------------------- TEMPLATES ---------------------------------- #
+# **************************************************************************** #
+define GITIGNORE_CONTENT
+# object files and archives in all directories
+*.o
+*.a
+
+# PDFs
+*.pdf
+
+# macOS specific files
+*.dSYM
+.DS_Store
+
+# Visual Studio Code settings
+.vscode
+
+# tmp, and obj directories in all directories
+**/tmp/
+**/obj/
+
+# output files
+out.txt
+
+# # Executables
+
+# Default executable
+a.out
+
+# $(MODULE) specific executables
+$(NAME)
+
+endef
+
+export GITIGNORE_CONTENT
+# **************************************************************************** #
 # **************************************************************************** #
 define CLASS_HEADER
 #ifndef CLASSNAME_UPPER_HPP
@@ -244,6 +303,7 @@ class CLASSNAME
 endef
 
 export CLASS_HEADER
+# **************************************************************************** #
 # **************************************************************************** #
 define CLASS_CPP
 #include "CLASSNAME.hpp"
@@ -295,6 +355,8 @@ ESC			:= \033
 # Text
 RESET		:= $(ESC)[0m
 BOLD		:= $(ESC)[1m
+ITALIC		:= $(ESC)[3m
+UNDERLINE	:= $(ESC)[4m
 
 RED			:= $(ESC)[91m
 GREEN		:= $(ESC)[32m
@@ -303,9 +365,14 @@ ORANGE		:= $(ESC)[38;5;208m
 BLUE		:= $(ESC)[94m
 PURPLE		:= $(ESC)[95m
 CYAN		:= $(ESC)[96m
+GRAYTALIC	:= $(ESC)[3;90m
 
 # Cursor movement
 UP			:= $(ESC)[A
 
 # Erasing
 ERASE_LINE	:= $(ESC)[2K
+
+# Hyperlinks (w.i.p)
+# HYPERLINK			:= \033]8;;
+# usage: $(HYPERLINK)file://$(FILEPATH)\a$(FILEPATH)$(HYPERLINK)\a
